const audio=document.querySelector('#audio');const fileInput=document.querySelector('#fileInput');const tracks=[];let current=-1;let favorites=new Set();
const $=s=>document.querySelector(s);const fmt=s=>{if(!isFinite(s))return'0:00';return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')};
function openFiles(){fileInput.click()}['#addBtn','#heroAddBtn','#emptyAddBtn'].forEach(s=>$(s)?.addEventListener('click',openFiles));
fileInput.addEventListener('change',e=>{[...e.target.files].forEach(file=>{if(!file.type.startsWith('audio/')&&!file.name.toLowerCase().endsWith('.mp3'))return;tracks.push({id:crypto.randomUUID(),file,url:URL.createObjectURL(file),title:file.name.replace(/\.mp3$/i,'')||'Untitled',artist:'Local MP3',duration:0});});render();if(tracks.length&&!audio.src)play(0);fileInput.value=''});
function play(i){if(!tracks[i])return;current=i;const t=tracks[i];audio.src=t.url;audio.play().catch(()=>{});$('#nowTitle').textContent=t.title;$('#nowArtist').textContent=t.artist;$('#playBtn').textContent='Ⅱ';updateLike();}
function toggle(){if(current<0){if(tracks.length)play(0);return}audio.paused?(audio.play(),$('#playBtn').textContent='Ⅱ'):(audio.pause(),$('#playBtn').textContent='▶')}
function next(){if(tracks.length)play((current+1)%tracks.length)}function prev(){if(tracks.length)play((current-1+tracks.length)%tracks.length)}
function toggleFavorite(i=current){if(i<0)return;favorites.has(tracks[i].id)?favorites.delete(tracks[i].id):favorites.add(tracks[i].id);updateLike();render()}
function updateLike(){if(current>=0)$('#likeBtn').textContent=favorites.has(tracks[current].id)?'♥':'♡'}
function card(t,i){return `<article class="track-card" data-i="${i}"><div class="cover">♫</div><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span></article>`}
function row(t,i){return `<div class="song-row"><div class="row-cover">♫</div><div class="row-meta"><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span></div><span>${fmt(t.duration)}</span><button class="icon-btn" data-like="${i}">${favorites.has(t.id)?'♥':'♡'}</button></div>`}
function render(){const q=$('#searchInput').value.trim().toLowerCase();const visible=tracks.map((t,i)=>({t,i})).filter(x=>x.t.title.toLowerCase().includes(q));$('#trackGrid').innerHTML=visible.map(x=>card(x.t,x.i)).join('');$('#libraryList').innerHTML=visible.map(x=>row(x.t,x.i)).join('');$('#favoritesList').innerHTML=tracks.map((t,i)=>({t,i})).filter(x=>favorites.has(x.t.id)&&x.t.title.toLowerCase().includes(q)).map(x=>row(x.t,x.i)).join('');$('#emptyState').style.display=tracks.length?'none':'block';$('#libraryCount').textContent=tracks.length?`${tracks.length} song${tracks.length===1?'':'s'}`:'No music added yet';document.querySelectorAll('.track-card').forEach(el=>el.onclick=()=>play(+el.dataset.i));document.querySelectorAll('[data-like]').forEach(el=>el.onclick=e=>{e.stopPropagation();toggleFavorite(+el.dataset.like)})}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#playBtn').onclick=toggle;$('#nextBtn').onclick=next;$('#prevBtn').onclick=prev;$('#likeBtn').onclick=()=>toggleFavorite();$('#searchInput').oninput=render;$('#volume').oninput=e=>audio.volume=e.target.value;audio.volume=.8;audio.addEventListener('loadedmetadata',()=>{$('#duration').textContent=fmt(audio.duration);if(current>=0)tracks[current].duration=audio.duration;render()});audio.addEventListener('timeupdate',()=>{$('#currentTime').textContent=fmt(audio.currentTime);$('#progress').value=audio.duration?(audio.currentTime/audio.duration)*100:0});audio.addEventListener('ended',next);$('#progress').oninput=e=>{if(audio.duration)audio.currentTime=(e.target.value/100)*audio.duration};
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$('#'+btn.dataset.view+'View').classList.add('active-view');render()});$('#themeBtn').onclick=()=>document.body.classList.toggle('light');
render();
